//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBMS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MBMSEntities : DbContext
    {
        public MBMSEntities()
            : base("name=MBMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdvanceMoneyCustomer> AdvanceMoneyCustomers { get; set; }
        public DbSet<BillCode7Layer> BillCode7Layer { get; set; }
        public DbSet<BillCode7LayerDetail> BillCode7LayerDetail { get; set; }
        public DbSet<CompanyProfile> CompanyProfiles { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Ledger> Ledgers { get; set; }
        public DbSet<Meter> Meters { get; set; }
        public DbSet<MeterBill> MeterBills { get; set; }
        public DbSet<MeterBox> MeterBoxes { get; set; }
        public DbSet<MeterType> MeterTypes { get; set; }
        public DbSet<MeterUnitCollect> MeterUnitCollects { get; set; }
        public DbSet<Pole> Poles { get; set; }
        public DbSet<PunishmentCustomer> PunishmentCustomers { get; set; }
        public DbSet<PunishmentRule> PunishmentRules { get; set; }
        public DbSet<Quarter> Quarters { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Township> Townships { get; set; }
        public DbSet<Transformer> Transformers { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserInRole> UserInRoles { get; set; }
        public DbSet<MeterHistory> MeterHistories { get; set; }
        public DbSet<MeterLossesMultiplierChangeHistory> MeterLossesMultiplierChangeHistories { get; set; }
        public DbSet<TransformerHistory> TransformerHistories { get; set; }
    
        public virtual int MeterBill_DeleteByFromDateToDate(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MeterBill_DeleteByFromDateToDate", fromDateParameter, toDateParameter);
        }
    
        public virtual int MeterUnitCollect_DeleteByCustomerIDFromDateToDate(string customerID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var customerIDParameter = customerID != null ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MeterUnitCollect_DeleteByCustomerIDFromDateToDate", customerIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual int BillCode7LayerDetail_DeleteByBillCode7LayerID(string billCode7LayerID)
        {
            var billCode7LayerIDParameter = billCode7LayerID != null ?
                new ObjectParameter("billCode7LayerID", billCode7LayerID) :
                new ObjectParameter("billCode7LayerID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BillCode7LayerDetail_DeleteByBillCode7LayerID", billCode7LayerIDParameter);
        }
    }
}
